# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH']="../platforms"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(624, 555)
        self.RSACIPHER = QtWidgets.QLabel(Dialog)
        self.RSACIPHER.setGeometry(QtCore.QRect(270, 20, 101, 16))
        self.RSACIPHER.setObjectName("RSACIPHER")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 70, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 47, 13))
        self.label_2.setObjectName("label_2")
        self.btn_gen_keys = QtWidgets.QPushButton(Dialog)
        self.btn_gen_keys.setGeometry(QtCore.QRect(410, 40, 75, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.txt_plain_text = QtWidgets.QTextEdit(Dialog)
        self.txt_plain_text.setGeometry(QtCore.QRect(70, 70, 141, 41))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QTextEdit(Dialog)
        self.txt_cipher_text.setGeometry(QtCore.QRect(70, 120, 141, 41))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_info = QtWidgets.QTextEdit(Dialog)
        self.txt_info.setGeometry(QtCore.QRect(350, 70, 141, 41))
        self.txt_info.setObjectName("txt_info")
        self.txt_sign = QtWidgets.QTextEdit(Dialog)
        self.txt_sign.setGeometry(QtCore.QRect(350, 120, 141, 41))
        self.txt_sign.setObjectName("txt_sign")
        self.btn_encrypt = QtWidgets.QPushButton(Dialog)
        self.btn_encrypt.setGeometry(QtCore.QRect(40, 190, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(Dialog)
        self.btn_decrypt.setGeometry(QtCore.QRect(140, 190, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(Dialog)
        self.btn_sign.setGeometry(QtCore.QRect(340, 190, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(Dialog)
        self.btn_verify.setGeometry(QtCore.QRect(450, 190, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(266, 70, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(270, 130, 47, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.RSACIPHER.setText(_translate("Dialog", "RSA CIPHER"))
        self.label.setText(_translate("Dialog", "plain :"))
        self.label_2.setText(_translate("Dialog", "cipher"))
        self.btn_gen_keys.setText(_translate("Dialog", "Gen"))
        self.btn_encrypt.setText(_translate("Dialog", "encrypt"))
        self.btn_decrypt.setText(_translate("Dialog", "decrypt"))
        self.btn_sign.setText(_translate("Dialog", "sign"))
        self.btn_verify.setText(_translate("Dialog", "veri"))
        self.label_3.setText(_translate("Dialog", "imfomation:"))
        self.label_4.setText(_translate("Dialog", "signature:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
